// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Length$Css from "./Length.res.mjs";

function shorthand(width, style, color) {
  var styleString = style === "dashed" ? "dashed" : (
      style === "dotted" ? "dotted" : "solid"
    );
  return {
          borderColor: color,
          borderStyle: styleString,
          borderWidth: Length$Css.toString(width)
        };
}

var none = {
  border: "none"
};

var Length;

export {
  Length ,
  shorthand ,
  none ,
}
/* No side effect */
