// Generated by ReScript, PLEASE EDIT WITH CARE


var small = {
  borderRadius: "4px"
};

var medium = {
  borderRadius: "8px"
};

var large = {
  borderRadius: "12px"
};

export {
  small ,
  medium ,
  large ,
}
/* No side effect */
