// Generated by ReScript, PLEASE EDIT WITH CARE


var none = {
  boxShadow: "none"
};

function md(color) {
  return {
          boxShadow: "0px 2px 3px 0 " + color
        };
}

export {
  none ,
  md ,
}
/* No side effect */
