// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Text__$Css from "./Text__.res.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as Length__$Css from "./Length__.res.mjs";
import * as Margin__$Css from "./Margin__.res.mjs";
import * as Display__$Css from "./Display__.res.mjs";
import * as Padding__$Css from "./Padding__.res.mjs";

var empty = {};

function merge(styles) {
  return Core__Array.reduce(styles, empty, (function (acc, style) {
                return Object.assign({}, acc, style);
              }));
}

var borderBox = {
  boxSizing: "border-box"
};

var flex = {
  display: "flex",
  alignItems: "center",
  justifyContent: "space-between"
};

function width(value) {
  return {
          width: Length__$Css.toString(value)
        };
}

var widthAuto = {
  width: "auto"
};

var fullWidth = merge([
      {
        width: "100%"
      },
      borderBox
    ]);

function minWidth(value) {
  return {
          minWidth: Length__$Css.toString(value)
        };
}

function maxWidth(value) {
  return {
          maxWidth: Length__$Css.toString(value)
        };
}

function height(value) {
  return {
          height: Length__$Css.toString(value)
        };
}

var heightAuto = {
  height: "auto"
};

var fullHeight = merge([
      {
        height: "100%"
      },
      borderBox
    ]);

function maxHeight(value) {
  return {
          maxHeight: Length__$Css.toString(value)
        };
}

function minHeight(value) {
  return {
          minHeight: Length__$Css.toString(value)
        };
}

function gap(value) {
  return {
          gap: Length__$Css.toString(value)
        };
}

var page = merge([
      Padding__$Css.xy(Length__$Css.md, Length__$Css.none),
      Display__$Css.css("block")
    ]);

var container = merge([
      Padding__$Css.xy(Length__$Css.md, Length__$Css.none),
      Display__$Css.css("block"),
      maxWidth(Length__$Css.container),
      Margin__$Css.xy("Auto", Length__$Css.none)
    ]);

var logo = merge([
      Text__$Css.Font.css("heading"),
      Text__$Css.Size.css("sm"),
      Text__$Css.Weight.css("bold")
    ]);

var navLink = merge([
      Text__$Css.Font.css("body"),
      Text__$Css.Size.css("sm"),
      Text__$Css.Weight.css("medium")
    ]);

var label = merge([
      Text__$Css.Font.css("body"),
      Text__$Css.Size.css("sm"),
      Text__$Css.Weight.css("medium")
    ]);

var h1 = merge([
      Text__$Css.Font.css("heading"),
      Text__$Css.Size.css("xxl"),
      Text__$Css.Weight.css("bold")
    ]);

var h2 = merge([
      Text__$Css.Font.css("heading"),
      Text__$Css.Size.css("xl"),
      Text__$Css.Weight.css("bold")
    ]);

var h3 = merge([
      Text__$Css.Font.css("heading"),
      Text__$Css.Size.css("lg"),
      Text__$Css.Weight.css("bold")
    ]);

var h4 = merge([
      Text__$Css.Font.css("heading"),
      Text__$Css.Size.css("md"),
      Text__$Css.Weight.css("bold")
    ]);

var h5 = merge([
      Text__$Css.Font.css("heading"),
      Text__$Css.Size.css("sm"),
      Text__$Css.Weight.css("bold")
    ]);

var h6 = merge([
      Text__$Css.Font.css("heading"),
      Text__$Css.Size.css("xs"),
      Text__$Css.Weight.css("bold")
    ]);

var button = merge([
      Text__$Css.Font.css("body"),
      Text__$Css.Size.css("md"),
      Text__$Css.Weight.css("medium")
    ]);

var p = merge([
      Text__$Css.Font.css("body"),
      Text__$Css.Size.css("sm"),
      Text__$Css.Weight.css("regular")
    ]);

var pL = merge([
      Text__$Css.Font.css("body"),
      Text__$Css.Size.css("md"),
      Text__$Css.Weight.css("regular")
    ]);

var Background;

var Border;

var BorderRadius;

var BoxShadow;

var Cursor;

var Display;

var Flex;

var Length;

var Margin;

var Padding;

var $$Text;

export {
  Background ,
  Border ,
  BorderRadius ,
  BoxShadow ,
  Cursor ,
  Display ,
  Flex ,
  Length ,
  Margin ,
  Padding ,
  $$Text ,
  empty ,
  merge ,
  borderBox ,
  flex ,
  width ,
  widthAuto ,
  fullWidth ,
  minWidth ,
  maxWidth ,
  height ,
  heightAuto ,
  fullHeight ,
  maxHeight ,
  minHeight ,
  gap ,
  page ,
  container ,
  logo ,
  navLink ,
  label ,
  h1 ,
  h2 ,
  h3 ,
  h4 ,
  h5 ,
  h6 ,
  button ,
  p ,
  pL ,
}
/* fullWidth Not a pure module */
