// Generated by ReScript, PLEASE EDIT WITH CARE


function toString(value) {
  if (value === "inlineBlock") {
    return "inline-block";
  } else if (value === "inlineFlex") {
    return "inline-flex";
  } else if (value === "inline") {
    return "inline";
  } else if (value === "block") {
    return "block";
  } else {
    return "flex";
  }
}

function css(value) {
  return {
          display: toString(value)
        };
}

export {
  toString ,
  css ,
}
/* No side effect */
