// Generated by ReScript, PLEASE EDIT WITH CARE


function toString(value) {
  if (typeof value !== "object") {
    return "auto";
  } else if (value.TAG === "Pixels") {
    return value._0.toString() + "px";
  } else {
    return value._0.toString() + "%";
  }
}

function px(value) {
  return {
          TAG: "Pixels",
          _0: value
        };
}

function pct(value) {
  return {
          TAG: "Percentage",
          _0: value
        };
}

var none = {
  TAG: "Pixels",
  _0: 0
};

var xs = {
  TAG: "Pixels",
  _0: 10
};

var sm = {
  TAG: "Pixels",
  _0: 20
};

var md = {
  TAG: "Pixels",
  _0: 30
};

var lg = {
  TAG: "Pixels",
  _0: 40
};

var xl = {
  TAG: "Pixels",
  _0: 50
};

var container = {
  TAG: "Pixels",
  _0: 1500
};

export {
  toString ,
  px ,
  pct ,
  none ,
  xs ,
  sm ,
  md ,
  lg ,
  xl ,
  container ,
}
/* No side effect */
